site_name: AdvanceRailway Docs
site_url: https://advance-railway.nikomaru.page
theme:
  name: material
  language: en
  logo: null
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant.preview
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search:
      lang: en
  - awesome-pages
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
        - locale: ja
          default: true
          name: 日本語
          build: true

repo_url: https://github.com/Nlkomaru/AdvanceRailway
repo_name: AdvanceRailway
copyright: No Rights Reserved(CC0).  Written by Nikomaru in 2024